auteur = "Auteur"
author = "Author"
bloctexte = "justify"
copyright = "Licence"
couverture = "/uploads/couverture.jpg"
description = "Description"
edition = "Fabrique"
format = "portrait"
indentation = "oui"
isbn = ""
licence = "Licence"
logo = "images/logo.jpg"
marques = "crop"
mention = "Fabrique"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = "Sous-titre"
titre = "Titre"
